// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonReviewApp.Data;

#nullable disable

namespace PokemonReviewApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PokemonReviewApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gym")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3016),
                            IsDeleted = false,
                            PermissionName = "ListCategory"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3029),
                            IsDeleted = false,
                            PermissionName = "AddCategory"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3029),
                            IsDeleted = false,
                            PermissionName = "UpdateCategory"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3030),
                            IsDeleted = false,
                            PermissionName = "DeleteCategory"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3031),
                            IsDeleted = false,
                            PermissionName = "ListCountry"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3033),
                            IsDeleted = false,
                            PermissionName = "AddCountry"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3034),
                            IsDeleted = false,
                            PermissionName = "UpdateCountry"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3035),
                            IsDeleted = false,
                            PermissionName = "DeleteCountry"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3035),
                            IsDeleted = false,
                            PermissionName = "ListFood"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3037),
                            IsDeleted = false,
                            PermissionName = "AddFood"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3038),
                            IsDeleted = false,
                            PermissionName = "UpdateFood"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3038),
                            IsDeleted = false,
                            PermissionName = "DeleteFood"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3039),
                            IsDeleted = false,
                            PermissionName = "ListOwner"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3040),
                            IsDeleted = false,
                            PermissionName = "AddOwner"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3041),
                            IsDeleted = false,
                            PermissionName = "UpdateOwner"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3041),
                            IsDeleted = false,
                            PermissionName = "DeleteOwner"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3042),
                            IsDeleted = false,
                            PermissionName = "ListPokemon"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3044),
                            IsDeleted = false,
                            PermissionName = "AddPokemon"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3045),
                            IsDeleted = false,
                            PermissionName = "UpdatePokemon"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3046),
                            IsDeleted = false,
                            PermissionName = "DeletePokemon"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3046),
                            IsDeleted = false,
                            PermissionName = "ListProperty"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3047),
                            IsDeleted = false,
                            PermissionName = "AddProperty"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3048),
                            IsDeleted = false,
                            PermissionName = "UpdateProperty"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3048),
                            IsDeleted = false,
                            PermissionName = "DeleteProperty"
                        },
                        new
                        {
                            Id = 25,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3049),
                            IsDeleted = false,
                            PermissionName = "ListReview"
                        },
                        new
                        {
                            Id = 26,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3050),
                            IsDeleted = false,
                            PermissionName = "AddReview"
                        },
                        new
                        {
                            Id = 27,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3050),
                            IsDeleted = false,
                            PermissionName = "UpdateReview"
                        },
                        new
                        {
                            Id = 28,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3051),
                            IsDeleted = false,
                            PermissionName = "DeleteReview"
                        },
                        new
                        {
                            Id = 29,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3052),
                            IsDeleted = false,
                            PermissionName = "ListReviewer"
                        },
                        new
                        {
                            Id = 30,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3053),
                            IsDeleted = false,
                            PermissionName = "AddReviewer"
                        },
                        new
                        {
                            Id = 31,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3053),
                            IsDeleted = false,
                            PermissionName = "UpdateReviewer"
                        },
                        new
                        {
                            Id = 32,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3054),
                            IsDeleted = false,
                            PermissionName = "DeleteReviewer"
                        });
                });

            modelBuilder.Entity("PokemonReviewApp.Models.PokeFood", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("PokeFoods");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.PokemonCategory", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PokemonCategories");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.PokemonLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PokemonLogs");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.PokemonOwner", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "OwnerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("PokemonOwners");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.PokeProperty", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "PropertyId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PokeProperties");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Reviewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reviewers");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3130),
                            IsDeleted = false,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3131),
                            IsDeleted = false,
                            RoleName = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDateTime = new DateTime(2025, 11, 14, 11, 51, 57, 223, DateTimeKind.Local).AddTicks(3132),
                            IsDeleted = false,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("PokemonReviewApp.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3215),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3217),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3218),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3218),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3218),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3220),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3220),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3220),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3221),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3222),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3222),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3222),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3223),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3223),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3248),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3248),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3249),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3250),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 19,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3250),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3251),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 21,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3251),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 22,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3251),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 23,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3252),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 24,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3252),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 25,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3252),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 26,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3253),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 27,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3253),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 28,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3253),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 29,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3253),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 30,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3254),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 31,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3254),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 32,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3254),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3266),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3269),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3271),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3274),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3275),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3277),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3278),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 10,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3279),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 11,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3280),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3282),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 14,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3282),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 15,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3284),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 17,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3286),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 18,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3287),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 19,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3288),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 21,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3291),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 22,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3292),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 23,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3293),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 25,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3297),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 26,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3298),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 27,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3299),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 29,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3301),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 30,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3302),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 31,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3303),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3428),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3429),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 9,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3429),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 13,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3430),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 17,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3430),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 21,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3430),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 25,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3431),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 26,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3431),
                            IsDeleted = false
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 29,
                            CreatedDateTime = new DateTime(2025, 11, 14, 8, 51, 57, 223, DateTimeKind.Utc).AddTicks(3431),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("PokemonReviewApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.UserLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Owner", b =>
                {
                    b.HasOne("PokemonReviewApp.Models.Country", "Country")
                        .WithMany("Owners")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.PokeFood", b =>
                {
                    b.HasOne("PokemonReviewApp.Models.Food", "Food")
                        .WithMany("PokeFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonReviewApp.Models.Pokemon", "Pokemon")
                        .WithMany("PokeFoods")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.PokemonCategory", b =>
                {
                    b.HasOne("PokemonReviewApp.Models.Category", "Category")
                        .WithMany("PokemonCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonReviewApp.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonCategories")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.PokemonOwner", b =>
                {
                    b.HasOne("PokemonReviewApp.Models.Owner", "Owner")
                        .WithMany("PokemonOwners")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonReviewApp.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonOwners")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.PokeProperty", b =>
                {
                    b.HasOne("PokemonReviewApp.Models.Pokemon", "Pokemon")
                        .WithMany("PokeProperties")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonReviewApp.Models.Property", "Property")
                        .WithMany("PokeProperties")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Review", b =>
                {
                    b.HasOne("PokemonReviewApp.Models.Pokemon", "Pokemon")
                        .WithMany("Reviews")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonReviewApp.Models.Reviewer", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.RolePermission", b =>
                {
                    b.HasOne("PokemonReviewApp.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonReviewApp.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.User", b =>
                {
                    b.HasOne("PokemonReviewApp.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Category", b =>
                {
                    b.Navigation("PokemonCategories");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Country", b =>
                {
                    b.Navigation("Owners");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Food", b =>
                {
                    b.Navigation("PokeFoods");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Owner", b =>
                {
                    b.Navigation("PokemonOwners");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Pokemon", b =>
                {
                    b.Navigation("PokeFoods");

                    b.Navigation("PokeProperties");

                    b.Navigation("PokemonCategories");

                    b.Navigation("PokemonOwners");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Property", b =>
                {
                    b.Navigation("PokeProperties");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Reviewer", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PokemonReviewApp.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
